# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib sentry.sdk, .registration = TRUE
NULL

#' Initialize the global Sentry client.
#' @export
sentry_init <- function(dsn, environment, release, debug, shutdown_timeout_ms, traces_sample_rate) .Call(wrap__sentry_init, dsn, environment, release, debug, shutdown_timeout_ms, traces_sample_rate)

#' Report whether the global Sentry client is enabled.
#' @export
sentry_enabled <- function() .Call(wrap__sentry_enabled)

#' Capture a Sentry message at the requested level.
#' @export
sentry_capture_message <- function(message, level) .Call(wrap__sentry_capture_message, message, level)

#' Flush pending Sentry envelopes.
#' @export
sentry_flush <- function(timeout_ms) .Call(wrap__sentry_flush, timeout_ms)

#' Close the global Sentry client.
#' @export
sentry_close <- function(timeout_ms) .Call(wrap__sentry_close, timeout_ms)

#' Start a transaction, optionally continuing an inbound `sentry-trace` header.
#' @export
sentry_transaction_start <- function(name, op, sentry_trace) .Call(wrap__sentry_transaction_start, name, op, sentry_trace)

#' Start a child span from an existing transaction or span.
#' @export
sentry_span_start_child <- function(parent, op, description) .Call(wrap__sentry_span_start_child, parent, op, description)

#' Set the active span on the current Sentry scope.
#' @export
sentry_set_current_span <- function(span) .Call(wrap__sentry_set_current_span, span)

#' Clear the active span from the current Sentry scope.
#' @export
sentry_clear_current_span <- function() .Call(wrap__sentry_clear_current_span)

#' Finish a transaction or span.
#' @export
sentry_span_finish <- function(span) .Call(wrap__sentry_span_finish, span)

# nolint end
